<?php
/**
 * @package LMI/LogManager/LogBook/LogMoniter
 * @copyright Copyright (c)2020 Amit Kumar Shukla. All Rights Reserved.
 * @license GNU General Public License version 3, or later
 * @contact akshukla.dev@gmail.com
 */

// no direct access
defined('_JEXEC') or die;

// Create shortcuts to some parameters.
$params = $this->item->params;
$item = $this->item;
?>

<div class="article-page<?php echo $this->pageclass_sfx; ?>">
  <meta itemprop="inLanguage" content="<?php echo ($item->language === '*') ? JFactory::getConfig()->get('language') : $item->language; ?>" />
  <?php echo $this->loadTemplate('title'); ?>
  <?php echo $this->loadTemplate('edit'); ?>
  <?php // Content is generated by content plugin event "onContentAfterTitle"?>
  <?php echo $item->event->afterDisplayTitle; ?>
  <?php // Content is generated by content plugin event "onContentBeforeDisplay"?>
  <?php echo $item->event->beforeDisplayContent; ?>
  <div itemprop="articleBody">
    <h3><?php echo JText::_('COM_LOGBOOK_DETAILS'); ?></h3>
      <ul class="list-group">
        <li class="list-group-item">
          <b><?php echo JText::_('COM_LOGBOOK_WATCHDOG'); ?><?php echo ': '; ?></b>
          <i><?php echo $item->watchdog_title; ?></i>
        </li>
        <li class="list-group-item">
          <b><?php echo JText::_('COM_LOGBOOK_INSET'); ?><?php echo ': '; ?></b>
          <i><?php echo $item->inset_title; ?></i>
        </li>
        <li class="list-group-item">
          <b><?php echo JText::_('COM_LOGBOOK_BPRINT'); ?><?php echo ': '; ?></b>
          <i><?php echo $item->bprint_title; ?></i>
        </li>
        <li class="list-group-item">
          <b><?php echo JText::_('COM_LOGBOOK_TINTERVAL'); ?><?php echo ': '; ?></b>
          <i><?php echo $item->tinterval_title; ?></i>
        </li>
        <li class="list-group-item">
          <b><?php echo JText::_('COM_LOGBOOK_WCENTER'); ?><?php echo ': '; ?></b>
          <i><?php echo $item->wcenter_title; ?></i>
        </li>
      </ul>

    <?php echo $this->loadTemplate('details'); ?>
    <div class="text">
      <h3><?php echo JText::_('COM_LOGBOOK_FIELD_REMARKS_LABEL'); ?></h3>
      <?php if (empty($item->remarks)): ?>
        <p>
          <?php echo '---'; ?>
        </p>
      <?php else: ?>
        <p>
          <?php echo $this->escape($item->remarks); ?>
        </p>
      <?php endif; ?>
    </div>
    <div class="text">
      <h3><?php echo JText::_('COM_LOGBOOK_FIELD_SIGNATORIES_LABEL'); ?></h3>
      <blockquote class="blockquote">
           <?php echo $this->escape($item->signatories); ?>
      </blockquote>
    </div>
  </div>
  <?php // Content is generated by content plugin event "onContentAfterDisplay"?>
  <?php echo $this->item->event->afterDisplayContent; ?>
</div>
