<?php
/**
 * @copyright Copyright (c)2017 Amit Kumar Shukla
 * @license GNU General Public License version 3, or later
 * @contact akshukla.dev@gmail.com
 */

// no direct access
defined('_JEXEC') or die;

// Create shortcuts to some parameters.
$params = $this->item->params;
$item = $this->item;
?>

<div class="item-page<?php echo $this->pageclass_sfx; ?>">
  <meta itemprop="inLanguage" content="<?php echo ($item->language === '*') ? JFactory::getConfig()->get('language') : $item->language; ?>" />
  <?php //if ($item->params->get('show_page_heading', 1)) :?>
    <div class=" row page-header">
      <h1 class="col11 span10">
          <?php // echo $this->escape($params->get('page_heading'));?>
      </h1>
    </div>
  <?php // endif;?>
  <div class="page-header">
    <?php echo $this->loadTemplate('title'); ?>
    <?php echo $this->loadTemplate('edit'); ?>
    <a href="<?php echo JUri::root().'/components/com_logbook/download/script.php?id='.$item->id; ?>" class="btn btn-success" target="_blank">
      <span class="icon-download"></span>&#160;<?php echo JText::_('COM_LOGBOOK_BUTTON_DOWNLOAD'); ?>
    </a>
  </div>
  <?php // Content is generated by content plugin event "onContentAfterTitle"?>
  <?php echo $item->event->afterDisplayTitle; ?>
  <?php // Content is generated by content plugin event "onContentBeforeDisplay"?>
  <?php echo $item->event->beforeDisplayContent; ?>
  <div itemprop="articleBody">
    <span class="label label-info"><?php echo JText::_('COM_LOGBOOK_DETAILS'); ?>
      <ul class="list-group">
        <li class="list-group-item">
          <span class="badge"><?php echo JText::_('COM_LOGBOOK_WATCHDOG'); ?></span>
          <?php echo $item->watchdog_title; ?>
        </li>
        <li class="list-group-item">
        <span class="badge"><?php echo JText::_('COM_LOGBOOK_INSET'); ?></span>
          <?php echo $item->inset_title; ?>
        </li>
        <li class="list-group-item">
          <span class="badge"><?php echo JText::_('COM_LOGBOOK_BPRINT'); ?></span>
          <?php echo $item->bprint_title; ?>
        </li>
        <li class="list-group-item">
          <span class="badge"><?php echo JText::_('COM_LOGBOOK_TINTERVAL'); ?></span>
          <?php echo $item->tinterval_title; ?>
        </li>
        <li class="list-group-item">
          <span class="badge"><?php echo JText::_('COM_LOGBOOK_WCENTER'); ?></span>
          <?php echo $item->wcenter_title; ?>
        </li>
      </ul>
    </span>
    <?php echo $this->loadTemplate('details'); ?>
    <div class="text">
      <div class="label">
            <?php echo JText::_('COM_LOGBOOK_FIELD_REMARKS_LABEL'); ?>
      </div>
      <?php if (empty($item->remarks)): ?>
      <div>
        <?php echo '---'; ?>
      </div>
      <?php else: ?>
        <div>
          <?php echo $this->escape($item->remarks); ?>
        </div>
      <?php endif; ?>
    </div>
    <div class="signatories">
      <div class="signatories-label">
           <?php echo JText::_('COM_LOGBOOK_FIELD_SIGNATORIES_LABEL'); ?>
      </div>
      <blockquote class="blockquote">
           <?php echo $this->escape($item->signatories); ?>
      </blockquote>
    </div>
  </div>
  <?php // Content is generated by content plugin event "onContentAfterDisplay"?>
  <?php echo $this->item->event->afterDisplayContent; ?>
</div>
