--
-- Table structure for table `#__logbook_logs`
--
CREATE TABLE IF NOT EXISTS `#__logbook_logs`(
	`id`	INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `asset_id` INT(10) UNSIGNED NOT NULL DEFAULT 0 ,
  `title` VARCHAR(255) NOT NULL DEFAULT '',
  `alias` VARCHAR(400) NOT NULL DEFAULT '' ,
	`remarks` TINYTEXT NOT NULL DEFAULT '' ,
	`catid` int(10) UNSIGNED NOT NULL DEFAULT 0,
	`wdid` INT(10) UNSIGNED NOT NULL DEFAULT 0,
  `file` VARCHAR(255) NOT NULL DEFAULT '',
  `file_name` VARCHAR(255) NOT NULL DEFAULT '',
  `file_type` VARCHAR(61) NOT NULL DEFAULT '',
  `file_size` VARCHAR(123) NOT NULL DEFAULT '',
  `file_path` VARCHAR(123) NOT NULL DEFAULT '',
  `file_icon` VARCHAR(61) NOT NULL DEFAULT '',
  `signatories` TINYTEXT NOT NULL DEFAULT '',
  `downloads` INT(10) UNSIGNED NOT NULL DEFAULT 0 ,
	`hits` INT(10) UNSIGNED NOT NULL DEFAULT 0 ,
  `access` TINYINT(3) NOT NULL DEFAULT 0 ,
	`state` TINYINT NOT NULL DEFAULT 0 ,
	`ordering` INT(11) NOT NULL DEFAULT 0 ,
  `created_by` INT(10) UNSIGNED NOT NULL DEFAULT 0,
	`created_by_alias` VARCHAR(400) NOT NULL DEFAULT '',
  `created` DATETIME NOT NULL DEFAULT '0000-00-00 00:00:00' ,
  `modified` DATETIME NOT NULL DEFAULT '0000-00-00 00:00:00' ,
	`checked_out` INT(10) UNSIGNED NOT NULL DEFAULT 0 ,
  `checked_out_time` DATETIME NOT NULL DEFAULT '0000-00-00 00:00:00' ,
  `modified_by` INT(10) UNSIGNED NOT NULL DEFAULT 0,
	`closed` DATETIME NOT NULL DEFAULT '0000-00-00 00:00:00',
  `closed_by` INT(10) UNSIGNED NOT NULL DEFAULT 0,
	`publish_down` DATETIME NOT NULL DEFAULT '0000-00-00 00:00:00',
	`params` TEXT NOT NULL ,
  `metakey` TEXT NOT NULL,
	`metadesc` TEXT NOT NULL ,
	`metadata` TEXT NOT NULL ,
	`language` CHAR(7) NOT NULL,
	`version` int(10) UNSIGNED NOT NULL DEFAULT 1,
  `note` varchar(255) NOT NULL DEFAULT '',
	PRIMARY KEY (`id`),
  KEY `idx_checkout` (`checked_out`),
  KEY `idx_access` (`access`),
	KEY `idx_state` (`state`),
	KEY `idx_wdid` (`wdid`),
	KEY `idx_catid` (`catid`),
  KEY `idx_createdby` (`created_by`),
	KEY `idx_language` (`language`),
	KEY `idx_alias` (`alias`(191))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 DEFAULT COLLATE=utf8mb4_unicode_ci;
