<?php
/**
 * @copyright   Copyright (C) 2005 - 2017 Open Source Matters, Inc. All rights reserved.
 * @license     GNU General Public License version 2 or later; see LICENSE.txt
 */
defined('_JEXEC') or die;

JHtml::addIncludePath(JPATH_COMPONENT.'/helpers');

// Create shortcuts to some parameters.
$params = $this->item->params;
$canEdit = $params->get('access-edit');
$user = JFactory::getUser();
$info = $params->get('info_block_position', 0);

// Check if associations are implemented. If they are, define the parameter.
$assocParam = (JLanguageAssociations::isEnabled() && $params->get('show_associations'));
JHtml::_('behavior.caption');

?>
<div class="item-page<?php echo $this->pageclass_sfx; ?>" itemscope itemtype="https://schema.org/Article">
    <meta itemprop="inLanguage" content="<?php echo ($this->item->language === '*') ? JFactory::getConfig()->get('language') : $this->item->language; ?>" />
    <?php if ($this->params->get('show_page_heading')) : ?>
    <div class="page-header">
        <h1> <?php echo $this->escape($this->params->get('page_heading')); ?> </h1>
    </div>
    <?php endif; ?>

    <?php // Todo Not that elegant would be nice to group the params?>
    <?php $useDefList = ($params->get('show_modify_date') || $params->get('show_publish_date') || $params->get('show_create_date')
    || $params->get('show_hits') || $params->get('show_category') || $params->get('show_parent_category') || $params->get('show_author') || $assocParam); ?>

    <?php if (!$useDefList && $this->print) : ?>
        <div id="pop-print" class="btn hidden-print">
            <?php echo JHtml::_('icon.print_screen', $this->item, $params); ?>
        </div>
        <div class="clearfix"> </div>
    <?php endif; ?>
    <?php if ($params->get('show_title') || $params->get('show_author')) : ?>
        <div class="page-header">
            <?php if ($params->get('show_title')) : ?>
                <h2 itemprop="headline">
                    <?php echo $this->escape($this->item->title); ?>
                </h2>
            <?php endif; ?>
            <?php if ($this->item->state == 0) : ?>
                <span class="label label-warning"><?php echo JText::_('JUNPUBLISHED'); ?></span>
            <?php endif; ?>
            <?php if (strtotime($this->item->publish_up) > strtotime(JFactory::getDate())) : ?>
                <span class="label label-warning"><?php echo JText::_('JNOTPUBLISHEDYET'); ?></span>
            <?php endif; ?>
            <?php if ((strtotime($this->item->publish_down) < strtotime(JFactory::getDate())) && $this->item->publish_down != JFactory::getDbo()->getNullDate()) : ?>
                <span class="label label-warning"><?php echo JText::_('JEXPIRED'); ?></span>
            <?php endif; ?>
        </div>
    <?php endif; ?>
    <?php if ($this->print) : ?>
        <?php if ($useDefList) : ?>
            <div id="pop-print" class="btn hidden-print">
                <?php echo JHtml::_('icon.print_screen', $this->item, $params); ?>
            </div>
        <?php endif; ?>
    <?php endif; ?>

    <?php // Content is generated by content plugin event "onContentAfterTitle"?>
    <?php echo $this->item->event->afterDisplayTitle; ?>

    <?php if ($useDefList && ($info == 0 || $info == 2)) : ?>
        <?php // Todo: for Joomla4 joomla.content.info_block.block can be changed to joomla.content.info_block?>
        <?php echo JLayoutHelper::render('joomla.content.info_block.block', array('item' => $this->item, 'params' => $params, 'position' => 'above')); ?>
    <?php endif; ?>

    <?php // Content is generated by content plugin event "onContentBeforeDisplay"?>
    <?php echo $this->item->event->beforeDisplayContent; ?>

    <?php //if ($params->get('access-view')) :?>
        <div itemprop="articleBody">
            <table class="table table-condensed">
                <tr>
                    <td><?php echo JText::_('COM_LOGMONITER_WATCHDOG_DETAILS_WCENTER'); ?></td>
                    <td><?php echo $this->escape($this->item->wcenter_title); ?></td>
                </tr>
                <tr>
                    <td><?php echo JText::_('COM_LOGMONITER_WATCHDOG_DETAILS_INSET'); ?></td>
                    <td><?php echo $this->escape($this->item->inset_title); ?></td>
                </tr>
                <tr>
                    <td><?php echo JText::_('COM_LOGMONITER_WATCHDOG_DETAILS_BPRINT'); ?></td>
                    <td><?php echo $this->escape($this->item->bprint_title); ?></td>
                </tr>
                <tr>
                    <td><?php echo JText::_('COM_LOGMONITER_WATCHDOG_DETAILS_TINTERVAL'); ?></td>
                    <td><?php echo $this->escape($this->item->tinterval_title); ?></td>
                </tr>
                <tr>
                    <td><?php echo JText::_('COM_LOGMONITER_WATCHDOG_DETAILS_LATEST_LOG_DATE'); ?></td>
                    <td><?php echo $this->escape($this->item->latest_log_date); ?></td>
                </tr>
                <tr>
                    <td><?php echo JText::_('COM_LOGMONITER_WATCHDOG_DETAILS_NEXT_DUE_DATE'); ?></td>
                    <td><?php echo $this->escape($this->item->next_due_date); ?></td>
                </tr>
                <tr>
                    <td><?php echo JText::_('COM_LOGMONITER_WATCHDOG_DETAILS_LOGS'); ?></td>
                    <td><?php echo $this->escape($this->item->log_count); ?></td>
                </tr>
            </table>
        </div>
        <?php if ($info == 1 || $info == 2) : ?>
            <?php if ($useDefList) : ?>
                    <?php // Todo: for Joomla4 joomla.content.info_block.block can be changed to joomla.content.info_block?>
                <?php echo JLayoutHelper::render('joomla.content.info_block.block', array('item' => $this->item, 'params' => $params, 'position' => 'below')); ?>
            <?php endif; ?>
            <?php if ($info == 0 && $params->get('show_tags', 1) && !empty($this->item->tags->itemTags)) : ?>
                <?php $this->item->tagLayout = new JLayoutFile('joomla.content.tags'); ?>
                <?php echo $this->item->tagLayout->render($this->item->tags->itemTags); ?>
            <?php endif; ?>
        <?php endif; ?>
    <?php //endif;?>
    <?php // Content is generated by content plugin event "onContentAfterDisplay"?>
    <?php echo $this->item->event->afterDisplayContent; ?>
</div>
