<?php
/**
 * @copyright   Copyright (C) 2005 - 2017 Open Source Matters, Inc. All rights reserved.
 * @license     GNU General Public License version 2 or later; see LICENSE.txt
 */
defined('_JEXEC') or die;

JHtml::addIncludePath(JPATH_COMPONENT.'/helpers');

// Create shortcuts to some parameters.
$params = $this->item->params;
$canEdit = $params->get('access-edit');
$user = JFactory::getUser();
$info = $params->get('info_block_position', 0);

// Check if associations are implemented. If they are, define the parameter.
$assocParam = (JLanguageAssociations::isEnabled() && $params->get('show_associations'));
JHtml::_('behavior.caption');

?>
<div class="item-page<?php echo $this->pageclass_sfx; ?>" itemscope itemtype="https://schema.org/Article">
    <meta itemprop="inLanguage" content="<?php echo ($this->item->language === '*') ? JFactory::getConfig()->get('language') : $this->item->language; ?>" />
    <?php if ($this->params->get('show_page_heading')) : ?>
    <div class="page-header">
        <h1> <?php echo $this->escape($this->params->get('page_heading')); ?> </h1>
    </div>
    <?php endif;
    if (!empty($this->item->pagination) && $this->item->pagination && !$this->item->paginationposition && $this->item->paginationrelative) {
        echo $this->item->pagination;
    }
    ?>

    <?php // Todo Not that elegant would be nice to group the params?>
    <?php
        $useDefList = (
            $params->get('show_modify_date')
            || $params->get('show_publish_date')
            || $params->get('show_create_date')
            || $params->get('show_latest_log_date')
            || $params->get('show_next_due_date')
            || $params->get('show_hits')
            || $params->get('logs')
            || $params->get('show_category')
            || $params->get('show_parent_category')
            || $params->get('show_wcenter') || $params->get('show_inset')
            || $params->get('show_bprint') || $params->get('show_tinterval')
            || $assocParam
        );
    ?>

    <?php if (!$useDefList && $this->print) : ?>
        <div id="pop-print" class="btn hidden-print">
            <?php echo JHtml::_('icon.print_screen', $this->item, $params); ?>
        </div>
        <div class="clearfix"> </div>
    <?php endif; ?>
    <?php if ($params->get('show_title') || $params->get('show_author')) : ?>
        <div class="page-header">
            <?php if ($params->get('show_title')) : ?>
                <h2 itemprop="headline">
                    <?php echo $this->escape($this->item->title); ?>
                </h2>
            <?php endif; ?>
            <?php if ($this->item->state == 0) : ?>
                <span class="label label-warning"><?php echo JText::_('JUNPUBLISHED'); ?></span>
            <?php endif; ?>
            <?php if (strtotime($this->item->publish_up) > strtotime(JFactory::getDate())) : ?>
                <span class="label label-warning"><?php echo JText::_('JNOTPUBLISHEDYET'); ?></span>
            <?php endif; ?>
            <?php if ((strtotime($this->item->publish_down) < strtotime(JFactory::getDate())) && $this->item->publish_down != JFactory::getDbo()->getNullDate()) : ?>
                <span class="label label-warning"><?php echo JText::_('JEXPIRED'); ?></span>
            <?php endif; ?>
        </div>
    <?php endif; ?>
    <?php if (!$this->print) : ?>
        <?php if ($canEdit || $params->get('show_print_icon') || $params->get('show_email_icon')) : ?>
            <?php echo JLayoutHelper::render('joomla.content.icons', array('params' => $params, 'item' => $this->item, 'print' => false)); ?>
        <?php endif; ?>
    <?php else : ?>
        <?php if ($useDefList) : ?>
            <div id="pop-print" class="btn hidden-print">
                <?php echo JHtml::_('icon.print_screen', $this->item, $params); ?>
            </div>
        <?php endif; ?>
    <?php endif; ?>

    <?php // Content is generated by content plugin event "onContentAfterTitle"?>
    <?php echo $this->item->event->afterDisplayTitle; ?>

    <?php if ($useDefList && ($info == 0 || $info == 2)) : ?>
        <?php // Todo: for Joomla4 joomla.content.info_block.block can be changed to joomla.content.info_block?>
        <?php echo JLayoutHelper::render('joomla.content.info_block.block', array('item' => $this->item, 'params' => $params, 'position' => 'above')); ?>
    <?php endif; ?>

    <?php if ($info == 0 && $params->get('show_tags', 1) && !empty($this->item->tags->itemTags)) : ?>
        <?php $this->item->tagLayout = new JLayoutFile('joomla.content.tags'); ?>
        <?php echo $this->item->tagLayout->render($this->item->tags->itemTags); ?>
    <?php endif; ?>

    <?php // Content is generated by content plugin event "onContentBeforeDisplay"?>
    <?php echo $this->item->event->beforeDisplayContent; ?>

    <?php if ($params->get('access-view')) : ?>
        <div class="container" itemprop="articleBody">
            <?php if ($params->get('show_wcenter')) : ?>
                <div class="row row-condensed">
                    <div class="col-xs-4 col-sm-4 col-md-4 col-lg-4">
                        <?php echo JText::_('COM_LOGMONITER_WATCHDOG_DETAILS_WCENTER'); ?>
                    </div>
                    <div class="col-xs-8 col-sm-8 col-md-8 col-lg-8">
                        <?php echo $this->escape($this->item->wcenter_title); ?>
                    </div>
                </div>
            <?php endif; ?>

            <?php if ($params->get('show_inset')) : ?>
                <div class="row row-condensed">
                    <div class="col-xs-4 col-sm-4 col-md-4 col-lg-4">
                        <?php echo JText::_('COM_LOGMONITER_WATCHDOG_DETAILS_INSET'); ?>
                    </div>
                    <div class="col-xs-8 col-sm-8 col-md-8 col-lg-8">
                        <?php echo $this->escape($this->item->inset_title); ?>
                    </div>
                </div>
            <?php endif; ?>

            <?php if ($params->get('show_bprint')) : ?>
                <div class="row row-condensed">
                    <div class="col-xs-4 col-sm-4 col-md-4 col-lg-4">
                        <?php echo JText::_('COM_LOGMONITER_WATCHDOG_DETAILS_BPRINT'); ?>
                    </div>
                    <div class="col-xs-8 col-sm-8 col-md-8 col-lg-8">
                        <?php echo $this->escape($this->item->bprint_title); ?>
                    </div>
                </div>
            <?php endif; ?>

            <?php if ($params->get('show_tinterval')) : ?>
                <div class="row row-condensed">
                    <div class="col-xs-4 col-sm-4 col-md-4 col-lg-4">
                        <?php echo JText::_('COM_LOGMONITER_WATCHDOG_DETAILS_TINTERVAL'); ?>
                    </div>
                    <div class="col-xs-8 col-sm-8 col-md-8 col-lg-8">
                        <?php echo $this->escape($this->item->tinterval_title); ?>
                    </div>
                </div>
            <?php endif; ?>

        </div>
    <?php endif; ?>
    <?php // Content is generated by content plugin event "onContentAfterDisplay"?>
    <?php echo $this->item->event->afterDisplayContent; ?>
</div>
