<?php
/**
 * @copyright   Copyright (C) 2005 - 2017 Open Source Matters, Inc. All rights reserved.
 * @license     GNU General Public License version 2 or later; see LICENSE.txt
 */
defined('_JEXEC') or die;

JHtml::addIncludePath(JPATH_COMPONENT.'/helpers');

// Create shortcuts to some parameters.
$params = $this->item->params;
$canEdit = $params->get('access-edit');
$user = JFactory::getUser();

// Check if associations are implemented. If they are, define the parameter.
$assocParam = (JLanguageAssociations::isEnabled() && $params->get('show_associations'));
JHtml::_('behavior.caption');

?>
<div class="item-page<?php echo $this->pageclass_sfx; ?>" itemscope itemtype="https://schema.org/Article">
    <meta itemprop="inLanguage" content="<?php echo ($this->item->language === '*') ? JFactory::getConfig()->get('language') : $this->item->language; ?>" />
    <?php if ($this->params->get('show_page_heading')) : ?>
    <div class="page-header">
        <h1> <?php echo $this->escape($this->params->get('page_heading')); ?> </h1>
    </div>
    <?php endif; ?>

    <div class="page-header">
		<h2 itemprop="headline">
			<?php echo $this->escape($this->item->title); ?>
		</h2>
        <?php if ($this->item->state == 0) : ?>
            <span class="label label-warning"><?php echo JText::_('JUNPUBLISHED'); ?></span>
        <?php endif; ?>
        <?php if (strtotime($this->item->publish_up) > strtotime(JFactory::getDate())) : ?>
            <span class="label label-warning"><?php echo JText::_('JNOTPUBLISHEDYET'); ?></span>
        <?php endif; ?>
        <?php if ((strtotime($this->item->publish_down) < strtotime(JFactory::getDate())) && $this->item->publish_down != JFactory::getDbo()->getNullDate()) : ?>
            <span class="label label-warning"><?php echo JText::_('JEXPIRED'); ?></span>
        <?php endif; ?>
    </div>

    <?php // Content is generated by content plugin event "onContentAfterTitle"?>
    <?php echo $this->item->event->afterDisplayTitle; ?>

    <?php // Todo: for Joomla4 joomla.content.info_block.block can be changed to joomla.content.info_block?>

    <ul class="list-group small">
        <li class="list-group-item">
            <span class="badge badge-info"><?php echo JText::_('COM_LOGMONITER_WATCHDOG_DETAILS_CATEGORY'); ?></span>
            <?php echo $this->escape($this->item->category_title); ?>
        </li>
        <li class="list-group-item">
            <span class="badge badge-success"><?php echo JText::_('COM_LOGMONITER_WATCHDOG_DETAILS_CREATED'); ?></span>
            <?php echo JHtml::_('date', $this->item->created, JText::_('DATE_FORMAT_LC3')); ?>
        </li>
        <li class="list-group-item">
            <span class="badge badge-warning"><?php echo JText::_('COM_LOGMONITER_WATCHDOG_DETAILS_AUTHOR'); ?></span>
            <?php echo $this->escape($this->item->author); ?>
        </li>
    </ul>

    <?php // Content is generated by content plugin event "onContentBeforeDisplay"?>
    <?php echo $this->item->event->beforeDisplayContent; ?>

    <?php //if ($params->get('access-view')) :?>
        <div itemprop="articleBody">
            <table class="table table-condensed">
                <tr>
                    <td><?php echo JText::_('COM_LOGMONITER_WATCHDOG_DETAILS_WCENTER'); ?></td>
                    <td><?php echo $this->escape($this->item->wcenter_title); ?></td>
                </tr>
                <tr>
                    <td><?php echo JText::_('COM_LOGMONITER_WATCHDOG_DETAILS_INSET'); ?></td>
                    <td><?php echo $this->escape($this->item->inset_title); ?></td>
                </tr>
                <tr>
                    <td><?php echo JText::_('COM_LOGMONITER_WATCHDOG_DETAILS_BPRINT'); ?></td>
                    <td><?php echo $this->escape($this->item->bprint_title); ?></td>
                </tr>
                <tr>
                    <td><?php echo JText::_('COM_LOGMONITER_WATCHDOG_DETAILS_TINTERVAL'); ?></td>
                    <td><?php echo $this->escape($this->item->tinterval_title); ?></td>
                </tr>
                <tr>
                    <td><?php echo JText::_('COM_LOGMONITER_WATCHDOG_DETAILS_LATEST_LOG_DATE'); ?></td>
                    <td><?php echo JHtml::_('date', $this->item->latest_log_date, JText::_('DATE_FORMAT_LC3')); ?></td>
                </tr>
                <tr>
                    <td><?php echo JText::_('COM_LOGMONITER_WATCHDOG_DETAILS_NEXT_DUE_DATE'); ?></td>
                    <td><?php echo JHtml::_('date', $this->item->next_due_date, JText::_('DATE_FORMAT_LC3')); ?></td>
                </tr>
                <tr>
                    <td><?php echo JText::_('COM_LOGMONITER_WATCHDOG_DETAILS_LOGS'); ?></td>
                    <td><?php echo (int) $this->item->log_count; ?></td>
                </tr>
            </table>
        </div>
        <?php if ($params->get('show_tags', 1) && !empty($this->item->tags->itemTags)) : ?>
            <?php $this->item->tagLayout = new JLayoutFile('joomla.content.tags'); ?>
            <?php echo $this->item->tagLayout->render($this->item->tags->itemTags); ?>
        <?php endif; ?>
    <?php //endif;?>
    <?php // Content is generated by content plugin event "onContentAfterDisplay"?>
    <?php echo $this->item->event->afterDisplayContent; ?>
</div>
