<?php
/**
 * @copyright   Copyright (C) 2005 - 2017 Open Source Matters, Inc. All rights reserved.
 * @license     GNU General Public License version 2 or later; see LICENSE.txt
 */
defined('_JEXEC') or die;

JHtml::addIncludePath(JPATH_COMPONENT.'/helpers');
$params = $this->params;
?>

<div id="moniter-items">
    <?php foreach ($this->items as $i => $item) : ?>
        <?php $info = $item->params->get('info_block_position', 0); ?>
        <div class="row<?php echo $i % 2; ?>" itemscope itemtype="https://schema.org/Article">
            <div class="page-header">
                <h2 itemprop="headline">
                    <?php if ($params->get('link_titles')) : ?>
                        <a href="<?php echo JRoute::_(LogmoniterHelperRoute::getWatchdogRoute($item->slug, $item->catid, $item->language)); ?>" itemprop="url">
                            <?php echo $this->escape($item->title); ?>
                        </a>
                    <?php else : ?>
                        <?php echo $this->escape($item->title); ?>
                    <?php endif; ?>
                </h2>

                <?php // Content is generated by content plugin event "onContentAfterTitle"?>
                <?php echo $item->event->afterDisplayTitle; ?>

                <?php if ($params->get('show_author') && !empty($item->author)) : ?>
                    <div class="createdby" itemprop="author" itemscope itemtype="https://schema.org/Person">
                    <?php $author = $item->created_by_alias ?: $item->author; ?>
                    <?php $author = '<span itemprop="name">'.$author.'</span>'; ?>
                        <?php if (!empty($item->contact_link) && $params->get('link_author') == true) : ?>
                            <?php echo JText::sprintf('COM_LOGMONITER_WRITTEN_BY', JHtml::_('link', $this->item->contact_link, $author, array('itemprop' => 'url'))); ?>
                        <?php else : ?>
                            <?php echo JText::sprintf('COM_LOGMONITER_WRITTEN_BY', $author); ?>
                        <?php endif; ?>
                    </div>
                <?php endif; ?>
            </div>
        <?php
            $useDefList = (
                $params->get('show_modify_date')
                || $params->get('show_publish_date')
                || $params->get('show_create_date')
                || $params->get('show_latest_log_date')
                || $params->get('show_next_due_date')
                || $params->get('show_hits')
                || $params->get('logs')
                || $params->get('show_category')
                || $params->get('show_parent_category')
                || $params->get('show_wcenter') || $params->get('show_inset')
                || $params->get('show_bprint') || $params->get('show_tinterval')
            );
        ?>
        <?php if ($useDefList && ($info == 0 || $info == 2)) : ?>
            <div class="article-info message">
                <dl class="article-info">
                <dt class="article-info-term">
                    <?php echo JText::_('COM_LOGMONITER_WATCHDOG_INFO'); ?>
                </dt>

                <?php if ($params->get('show_parent_category') && !empty($item->parent_slug)) : ?>
                    <dd>
                        <div class="parent-category-name">
                            <?php $title = $this->escape($item->parent_title); ?>
                            <?php if ($params->get('link_parent_category') && !empty($item->parent_slug)) : ?>
                                <?php $url = '<a href="'.JRoute::_(LogmoniterHelperRoute::getCategoryRoute($item->parent_slug)).'" itemprop="genre">'.$title.'</a>'; ?>
                                <?php echo JText::sprintf('COM_LOGMONITER_PARENT', $url); ?>
                            <?php else : ?>
                                <?php echo JText::sprintf('COM_LOGMONITER_PARENT', '<span itemprop="genre">'.$title.'</span>'); ?>
                            <?php endif; ?>
                        </div>
                    </dd>
                <?php endif; ?>
                <?php if ($params->get('show_category')) : ?>
                    <dd>
                        <div class="category-name">
                            <?php $title = $this->escape($item->category_title); ?>
                            <?php if ($params->get('link_category') && $item->catslug) : ?>
                                <?php $url = '<a href="'.JRoute::_(LogmoniterHelperRoute::getCategoryRoute($item->catslug)).'" itemprop="genre">'.$title.'</a>'; ?>
                                <?php echo JText::sprintf('COM_LOGMONITER_CATEGORY', $url); ?>
                            <?php else : ?>
                                <?php echo JText::sprintf('COM_LOGMONITER_CATEGORY', '<span itemprop="genre">'.$title.'</span>'); ?>
                            <?php endif; ?>
                        </div>
                    </dd>
                <?php endif; ?>
                <?php if ($params->get('show_wcenter')) : ?>
                    <dd>
                        <div class="category-name">
                            <?php $title = $this->escape($item->wcenter_title); ?>
                            <?php echo JText::sprintf('COM_LOGMONITER_WCENTER', '<span itemprop="genre">'.$title.'</span>'); ?>
                        </div>
                    </dd>
                <?php endif; ?>
                <?php if ($params->get('show_inset')) : ?>
                    <dd>
                        <div class="category-name">
                            <?php $title = $this->escape($item->inset_title); ?>
                            <?php echo JText::sprintf('COM_LOGMONITER_INSET', '<span itemprop="genre">'.$title.'</span>'); ?>
                        </div>
                    </dd>
                <?php endif; ?>
                <?php if ($params->get('show_bprint')) : ?>
                    <dd>
                        <div class="category-name">
                            <?php $title = $this->escape($item->bprint_title); ?>
                            <?php echo JText::sprintf('COM_LOGMONITER_BPRINT', '<span itemprop="genre">'.$title.'</span>'); ?>
                        </div>
                    </dd>
                <?php endif; ?>
                <?php if ($params->get('show_tinterval')) : ?>
                    <dd>
                        <div class="category-name">
                            <?php $title = $this->escape($item->category_title); ?>
                            <?php echo JText::sprintf('COM_LOGMONITER_TINTERVAL', '<span itemprop="genre">'.$title.'</span>'); ?>
                        </div>
                    </dd>
                <?php endif; ?>

                <?php if ($params->get('show_logs')) : ?>
                        <dd>
                            <div class="logs">
                                <span class="icon-eye-close"></span>
                                <meta itemprop="interactionCount" content="UserPageVisits:<?php echo $item->log_count; ?>" />
                                <?php echo JText::sprintf('COM_LOGMONITER_WATCHDOG_LOG_COUNT', $item->log_count); ?>
                            </div>
                        </dd>
                <?php endif; ?>

                <?php if ($params->get('show_latest_log_date')) : ?>
                    <dd>
                        <div class="published">
                            <span class="icon-calendar" aria-hidden="true"></span>
                            <time datetime="<?php echo JHtml::_('date', $item->latest_log_date, 'c'); ?>" itemprop="datePublished">
                                <?php echo JText::sprintf('COM_LOGMONITER_LATEST_LOG_DATE_ON', JHtml::_('date', $item->latest_log_date, JText::_('DATE_FORMAT_LC3'))); ?>
                            </time>
                        </div>
                    </dd>
                <?php endif; ?>

                <?php if ($params->get('show_next_due_date')) : ?>
                    <dd>
                        <div class="published">
                            <span class="icon-calendar" aria-hidden="true"></span>
                            <time datetime="<?php echo JHtml::_('date', $item->next_due_date, 'c'); ?>" itemprop="datePublished">
                                <?php echo JText::sprintf('COM_LOGMONITER_NEXT_DUE_DATE_ON', JHtml::_('date', $item->next_due_date, JText::_('DATE_FORMAT_LC3'))); ?>
                            </time>
                        </div>
                    </dd>
                <?php endif; ?>

                <?php if ($params->get('show_publish_date')) : ?>
                    <dd>
                        <div class="published">
                            <span class="icon-calendar" aria-hidden="true"></span>
                            <time datetime="<?php echo JHtml::_('date', $item->publish_up, 'c'); ?>" itemprop="datePublished">
                                <?php echo JText::sprintf('COM_LOGMONITER_PUBLISHED_DATE_ON', JHtml::_('date', $item->publish_up, JText::_('DATE_FORMAT_LC3'))); ?>
                            </time>
                        </div>
                    </dd>
                <?php endif; ?>

                <?php if ($info == 0) : ?>
                    <?php if ($params->get('show_modify_date')) : ?>
                        <dd>
                            <div class="modified">
                                <span class="icon-calendar" aria-hidden="true"></span>
                                <time datetime="<?php echo JHtml::_('date', $item->modified, 'c'); ?>" itemprop="dateModified">
                                    <?php echo JText::sprintf('COM_LOGMONITER_LAST_UPDATED', JHtml::_('date', $item->modified, JText::_('DATE_FORMAT_LC3'))); ?>
                                </time>
                            </div>
                        </dd>
                    <?php endif; ?>
                    <?php if ($params->get('show_create_date')) : ?>
                        <dd>
                            <div class="create">
                                <span class="icon-calendar" aria-hidden="true"></span>
                                <time datetime="<?php echo JHtml::_('date', $item->created, 'c'); ?>" itemprop="dateCreated">
                                    <?php echo JText::sprintf('COM_LOGMONITER_CREATED_DATE_ON', JHtml::_('date', $item->created, JText::_('DATE_FORMAT_LC3'))); ?>
                                </time>
                            </div>
                        </dd>
                    <?php endif; ?>

                    <?php if ($params->get('show_hits')) : ?>
                        <dd>
                            <div class="hits">
                                <span class="icon-eye-open"></span>
                                <meta itemprop="interactionCount" content="UserPageVisits:<?php echo $item->hits; ?>" />
                                <?php echo JText::sprintf('COM_LOGMONITER_WATCHDOG_HITS', $item->hits); ?>
                            </div>
                        </dd>
                    <?php endif; ?>
                <?php endif; ?>
                </dl>
            </div>
        <?php endif; ?>

        <?php // Content is generated by content plugin event "onContentBeforeDisplay"?>
        <?php echo $item->event->beforeDisplayContent; ?>

        <?php if ($useDefList && ($info == 1 || $info == 2)) : ?>
            <div class="article-info message">
                <dl class="article-info">
                <dt class="article-info-term"><?php echo JText::_('COM_LOGMONITER_WATCHDOG_INFO'); ?></dt>

                <?php if ($info == 1) : ?>
                    <?php if ($params->get('show_parent_category') && !empty($item->parent_slug)) : ?>
                        <dd>
                            <div class="parent-category-name">
                                <?php $title = $this->escape($item->parent_title); ?>
                                <?php if ($params->get('link_parent_category') && $item->parent_slug) : ?>
                                    <?php $url = '<a href="'.JRoute::_(LogmoniterHelperRoute::getCategoryRoute($item->parent_slug)).'" itemprop="genre">'.$title.'</a>'; ?>
                                    <?php echo JText::sprintf('COM_LOGMONITER_PARENT', $url); ?>
                                <?php else : ?>
                                    <?php echo JText::sprintf('COM_LOGMONITER_PARENT', '<span itemprop="genre">'.$title.'</span>'); ?>
                                <?php endif; ?>
                            </div>
                        </dd>
                    <?php endif; ?>
                    <?php if ($params->get('show_category')) : ?>
                        <dd>
                            <div class="category-name">
                                <?php $title = $this->escape($item->category_title); ?>
                                <?php if ($params->get('link_category') && $item->catslug) : ?>
                                    <?php $url = '<a href="'.JRoute::_(LogmoniterHelperRoute::getCategoryRoute($item->catslug)).'" itemprop="genre">'.$title.'</a>'; ?>
                                    <?php echo JText::sprintf('COM_LOGMONITER_CATEGORY', $url); ?>
                                <?php else : ?>
                                    <?php echo JText::sprintf('COM_LOGMONITER_CATEGORY', '<span itemprop="genre">'.$title.'</span>'); ?>
                                <?php endif; ?>
                            </div>
                        </dd>
                    <?php endif; ?>
                    <?php if ($params->get('show_publish_date')) : ?>
                        <dd>
                            <div class="published">
                                <span class="icon-calendar" aria-hidden="true"></span>
                                <time datetime="<?php echo JHtml::_('date', $item->publish_up, 'c'); ?>" itemprop="datePublished">
                                    <?php echo JText::sprintf('COM_LOGMONITER_PUBLISHED_DATE_ON', JHtml::_('date', $item->publish_up, JText::_('DATE_FORMAT_LC3'))); ?>
                                </time>
                            </div>
                        </dd>
                    <?php endif; ?>
                <?php endif; ?>

                <?php if ($params->get('show_create_date')) : ?>
                    <dd>
                        <div class="create">
                            <span class="icon-calendar" aria-hidden="true"></span>
                            <time datetime="<?php echo JHtml::_('date', $item->created, 'c'); ?>" itemprop="dateCreated">
                                <?php echo JText::sprintf('COM_LOGMONITER_CREATED_DATE_ON', JHtml::_('date', $item->modified, JText::_('DATE_FORMAT_LC3'))); ?>
                            </time>
                        </div>
                    </dd>
                <?php endif; ?>
                <?php if ($params->get('show_modify_date')) : ?>
                    <dd>
                        <div class="modified">
                            <span class="icon-calendar" aria-hidden="true"></span>
                            <time datetime="<?php echo JHtml::_('date', $item->modified, 'c'); ?>" itemprop="dateModified">
                                <?php echo JText::sprintf('COM_LOGMONITER_LAST_UPDATED', JHtml::_('date', $item->modified, JText::_('DATE_FORMAT_LC3'))); ?>
                            </time>
                        </div>
                    </dd>
                <?php endif; ?>
                <?php if ($params->get('show_hits')) : ?>
                    <dd>
                        <div class="hits">
                            <span class="icon-eye-open"></span>
                            <meta content="UserPageVisits:<?php echo $item->hits; ?>" itemprop="interactionCount" />
                            <?php echo JText::sprintf('COM_LOGMONITER_WATCHDOG_HITS', $item->hits); ?>
                        </div>
                    </dd>
                <?php endif; ?>
            </dl>
        </div>
        <?php endif; ?>
        <?php // Content is generated by content plugin event "onContentAfterDisplay"?>
        <?php echo $item->event->afterDisplayContent; ?>
    </div>
    <?php endforeach; ?>
</div>
<div class="pagination">
    <p class="counter"> <?php echo $this->pagination->getPagesCounter(); ?> </p>
    <?php echo $this->pagination->getPagesLinks(); ?>
</div>
